После установки необходимого ПО можно описать свой код в директории */program*. 

== Запуск в SPIKE
Когда код написан, то его требуется скомпилировать. Для этого есть *Makefile* в директории */program*.

[source,bash]
----
make
----
Если происходило дополнительное подключение библиотек или что-то подобное, то нужно скорректировать строчку, вызывающую компиляцию.
_Изменять имя выходного файла(*main*) не рекомендуется_
[source,bash]
----
riscv32-unknown-elf-gcc -march=rv32im main.c -g -O0 -o main
----

В ходе выполнения _make_ произойдет следующее:

. Сгенерируется *obj файл* main
. Сгенерируется *disassemble* программы(для возможности изучения запускаемого кода)
. Сгенерируется файл *mem.v* для запуска кода на RTL процессоре.
. Выполнится bash скрипт для запуска кода в SPIKE и созранения лога выполнения

Лог получается с помощью утилиты expect, которая предназначена для общения с интерактивными программами. Это требуется для сохранения значения всех регистров на этапе выполнения кода.

Прим.
_На данный момент получение лога не совсем корректное ввиду несовершенства владения утилитой expect. Требуется доработка(а может быть и так сойдет :))_

== Запуск на RTL процессоре
Переходим в папку */sim*. Для запуска всего процесса есть *Makefile*.
[source,bash]
----
make modelsim
----
В ходе выполнения произойдет следующее:

. Вызов *Makefile* в дирекотрии */program* (что произойдет см. раздел *Запуск в SPIKE*)
. Запуск *Modelsim*
. Запуск скрипта сравнения результатов от RTL процессора и SPIKE.

Modelsim запустится с помощью скрипта(в зависимости от системы .sh или .bat). При желании можно скорректировать *modelsim.tcl*, где указаны папки с verilog файлами и выводимые при запуске сигналы.

Прим.
_Если что-то при запуске идет не так, то следует обратить внимание на стартовый адрес, указанный в /testbench/rv_core_testbench.sv_
----
assign boot_addr = 'h1018c; 
----
